# Generated by Django 6.0.2 on 2026-02-20 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verify Email'), ('reset', 'Reset Password')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
