# Generated by Django 6.0.2 on 2026-02-20 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapplication', '0002_customuser_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='max_try_out',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_try_max',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='purpose',
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('verify', 'Verify Email'), ('reset', 'Reset Password')])),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp_try_max', models.CharField(default=10, max_length=2)),
                ('max_try_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
