# Generated by Django 6.0.2 on 2026-02-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapplication', '0003_remove_customuser_max_try_out_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
